name: CI
on:
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{secrets.PRIVATE_SSH_KEY}}
    - run: echo ${SSH_PRIVATE_KEY}
    - run: ls ${GITHUB_WORKSPACE} 
    - run: echo ${GITHUB_WORKSPACE} 
    - run: ${GITHUB_WORKSPACE}/act.sh